CLUSTER_NAME: mgmt-cluster
CNI: antrea

INFRASTRUCTURE_PROVIDER: vsphere
DEPLOY_TKG_ON_VSPHERE7: true

VSPHERE_SERVER: 192.168.0.30
VSPHERE_USERNAME: administrator@vsphere.local
VSPHERE_PASSWORD: Passw0rd!

VSPHERE_DATACENTER: Datacenter
VSPHERE_DATASTORE: datastore20
VSPHERE_FOLDER: /Datacenter/vm/
VSPHERE_CLUSTER: devops
VSPHERE_RESOURCE_POOL: devops/Resources

VSPHERE_NETWORK: mgmt  # For bootstrap VM only

VSPHERE_CONTROL_PLANE_ENDPOINT: 192.168.0.200
CONTROL_PLANE_MACHINE_TYPE: small
WORKER_MACHINE_TYPE: small

VSPHERE_SSH_AUTHORIZED_KEY: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCaJ6PiE0C9ZtrnpUVtFm2mZSNLeiI2OgV1MgBSdT0zmnWB+YVUMd/oq/co44eMTlQDxOIV5hLqtWQqAMxtRTSpI4MrJoFB2rlP8mIeVFsNOjiXZTQuLHKt+2J1hOOHpu0aghIKzZugqRznH//S7ykVPB9dunKW7AfONaOg61FjUyjng8CAqso/AHVJPwbXF6kNjq+mizd+QD6wKtL+V5WQCuKwrGYpg90eAvtLj+9Zmnep6w7uZ0XL7f9UFMUqn0K7ghoPAZcbHGn01Z/g2Y8sLrFoArWmHzWamdaaXzRUfWs3KUUPKQDZ0r0kqZJ3mZCLMFenDzUtp0Yg2qdAoGMLtISwTXkQCmIuGdGTitfn6W/LXCjto4EQsM2RW8r2C/h5L8KojbnbTXDDlmc5mhc+sspHo3+4WO/54lhHCFOn3OC1GwlNvYY9COrGARjt7dWd5MRnbRP9OZfj5+5jcePLuzSqozEgpnpeFy8767tlvRwzyREBVd7R9V7GPWZdTtC0qDXzd+V7gzwJMTzyLSiTIr3ZikjrcA524WitOqezMXznL+S3P2mYFB/nJ3sR99ENrDVSlvOi2HwZ7xkdbjBPZAoAf24iUmYQMUvAjIgqTJgbaMPvYdPPjQW0tXEp1isw7DBluHj3m2F0HozkrkGuU/CR6PTCZWwSDg5KRfI+FQ== tkg-user"

ENABLE_AUDIT_LOGGING: true
ENABLE_DEFAULT_STORAGE_CLASS: true

# Node counts
VSPHERE_NUM_CPUS: "2"
VSPHERE_MEM_MIB: "4096"
VSPHERE_DISK_GIB: "40"

# HAProxy load balancer integration
VSPHERE_TLS_THUMBPRINT: ""  # Optional if using secure CA
VSPHERE_INSECURE: true

VSPHERE_HAPROXY_ENDPOINT: https://192.168.0.50:5556
VSPHERE_HAPROXY_USERNAME: admin
VSPHERE_HAPROXY_PASSWORD: YOUR_HAPROXY_PASSWORD  # Replace or use prompt
VSPHERE_HAPROXY_IP_POOL: 192.168.0.200/28
VSPHERE_HAPROXY_WORKLOAD_NETWORK_NAME: backend
VSPHERE_HAPROXY_FRONTEND_NETWORK_NAME: frontend
VSPHERE_HAPROXY_MANAGEMENT_NETWORK_NAME: mgmt
VSPHERE_HAPROXY_MANAGEMENT_NETWORK_GATEWAY: 192.168.0.1
VSPHERE_HAPROXY_WORKLOAD_NETWORK_GATEWAY: 192.168.0.1
VSPHERE_HAPROXY_FRONTEND_NETWORK_GATEWAY: 192.168.0.1
VSPHERE_HAPROXY_NETWORK_CIDR: 192.168.0.0/24

# OS image name (you must upload this to vSphere manually)
VSPHERE_TEMPLATE: photon-3-kube-v1.26.5+vmware.1-tkg.1

# Disable CEIP and telemetry if desired
CEIP_OPT_IN: false
ENABLE_MCE: false
