CLUSTER_NAME: tanzu-mgmt

# vSphere Info
VSPHERE_SERVER: 192.168.0.30
VSPHERE_USERNAME: administrator@vsphere.local
VSPHERE_PASSWORD: "Passw0rd!"  
VSPHERE_DATACENTER: Datacenter
VSPHERE_DATASTORE: datastore20
VSPHERE_FOLDER: /Datacenter/vm/
VSPHERE_NETWORK: mgmt
VSPHERE_RESOURCE_POOL: devops/Resources
VSPHERE_INSECURE: true

# Template
VSPHERE_TEMPLATE: photon-3-amd64-vmi-k8s-v1.26.5---vmware.2-fips.1-tkg.1

# SSH Key
VSPHERE_SSH_AUTHORIZED_KEY: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCaJ6PiE0C9ZtrnpUVtFm2mZSNLeiI2OgV1MgBSdT0zmnWB+YVUMd/oq/co44eMTlQDxOIV5hLqtWQqAMxtRTSpI4MrJoFB2rlP8mIeVFsNOjiXZTQuLHKt+2J1hOOHpu0aghIKzZugqRznH//S7ykVPB9dunKW7AfONaOg61FjUyjng8CAqso/AHVJPwbXF6kNjq+mizd+QD6wKtL+V5WQCuKwrGYpg90eAvtLj+9Zmnep6w7uZ0XL7f9UFMUqn0K7ghoPAZcbHGn01Z/g2Y8sLrFoArWmHzWamdaaXzRUfWs3KUUPKQDZ0r0kqZJ3mZCLMFenDzUtp0Yg2qdAoGMLtISwTXkQCmIuGdGTitfn6W/LXCjto4EQsM2RW8r2C/h5L8KojbnbTXDDlmc5mhc+sspHo3+4WO/54lhHCFOn3OC1GwlNvYY9COrGARjt7dWd5MRnbRP9OZfj5+5jcePLuzSqozEgpnpeFy8767tlvRwzyREBVd7R9V7GPWZdTtC0qDXzd+V7gzwJMTzyLSiTIr3ZikjrcA524WitOqezMXznL+S3P2mYFB/nJ3sR99ENrDVSlvOi2HwZ7xkdbjBPZAoAf24iUmYQMUvAjIgqTJgbaMPvYdPPjQW0tXEp1isw7DBluHj3m2F0HozkrkGuU/CR6PTCZWwSDg5KRfI+FQ== tkg-user"

# Cluster Endpoint
CONTROL_PLANE_ENDPOINT: 192.168.0.200

# Load Balancer (external HAProxy)
INFRASTRUCTURE_PROVIDER: vsphere
ENABLE_CEIP_PARTICIPATION: false
IDENTITY_MANAGEMENT_TYPE: none

# Optional Resource Specs
VSPHERE_NUM_CPUS: "2"
VSPHERE_MEM_MIB: "4096"
VSPHERE_DISK_GIB: "40"

# Load Balancer Config for External HAProxy
AVI_CONTROL_PLANE_HA_PROVIDER: "true"

# External HAProxy Details
LB_PROVIDER: haproxy
HAPROXY_USERNAME: admin
HAPROXY_PASSWORD: "Passw0rd!" 
HAPROXY_SERVER: 192.168.0.50
HAPROXY_PORT: 5556
HAPROXY_ALLOW_UNVERIFIED_SSL: "true"

# Load Balancer IP Pool (VIPs for control plane and services)
SERVICE_CIDR: 100.96.0.0/12
CLUSTER_CIDR: 100.64.0.0/13
VIP_CIDR: 192.168.0.200/28  # Your VIP range from HAProxy config
